# Generated by Django 5.2.4 on 2026-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('value_chain', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
